import keymirror from 'keymirror';

export const ACTION_TYPES = keymirror(
  {
    FETCH_SCHOLARSHIPS_SUCCESS: null,
    FETCH_SCHOLARSHIPS: null,
    FETCH_TOP_SCHOLARSHIPS_SUCCESS: null,
    DISPLAY_SIGNUP_MODAL: null,
    DISPLAY_LOGIN_MODAL: null,
    HIDE_AUTH_MODAL: null,
    FACEBOOK_LOGIN: null,
    LOGOUT: null,
    DELETE_USER: null,
    FETCH_LOGGED_IN_USER: null,
    FETCH_LOGGED_IN_USER_SUCCESS: null,
    FETCH_LOGGED_IN_USER_ERROR: null,
    FETCH_CATEGORIES_SUCCESS: null,
    FETCH_COMMON_DATA: null,
    FETCH_SUBCATEGORIES_SUCCESS: null,
    FETCH_GENDERS_SUCCESS: null,

    TOGGLE_HEADER_LINKS_VISIBILITY: null,
    SET_HEADER_LINKS: null,
    CONFIRM_EMAIL: null,

    UPDATE_USER_ADDITIONAL_INFO_SUCCESS: null,
    UPDATE_USER_ADDITIONAL_INFO: null,
    UPDATE_USER_ADDITIONAL_INFO_ERROR: null,

  }
);
